name: Deploy Backend

on:
  push:
    branches: [develop, homolog, main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PROJECT_PATH: /home/jony/freelaverse/backend

    steps:
      - name: Detect branch
        id: vars
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "develop" ]; then PROFILE="dev";
          elif [ "$BRANCH" = "homolog" ]; then PROFILE="hml";
          elif [ "$BRANCH" = "main" ]; then PROFILE="prod";
          else echo "Branch invÃ¡lida"; exit 1; fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "profile=$PROFILE" >> $GITHUB_OUTPUT

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      - name: Deploy backend
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" << 'EOF'
            set -e
            cd /home/jony/freelaverse/backend
            git pull origin ${{ steps.vars.outputs.branch }}
            cd ..
            cd infra
            docker compose --profile ${{ steps.vars.outputs.profile }} --env-file .env.${{ steps.vars.outputs.profile }} up --build -d
          EOF